### ISSUE TITLE
Error building on windows

### ISSUE THREAD

**Issue by DJWassink** [kiliman/operator-mono-lig#34]
Don't know if this is anything related to windows or that I did something wrong. But i get the following error while building:

```
Building OperatorMonoLig-Book
Dumping ".\original\OperatorMono-Book.otf" to ".\original\OperatorMono-Book.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
Dumping 'DSIG' table...
Reading original font file ./original/OperatorMono-Book.ttx
Patching names
Patching glyphs
Patching gpos
Patching gsub
Patching hmtx
Patching charstrings
Writing ligature font file ./build/OperatorMonoLig-Book.ttx
Done
Compiling ".\build\OperatorMonoLig-Book.ttx" to ".\build\OperatorMonoLig-Book.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'hmtx' table...
Parsing 'DSIG' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\fontTools\ttx.py", line 389, in main
    process(jobs, options)
  File "c:\python27\lib\site-packages\fontTools\ttx.py", line 363, in process
    action(input, output, options)
  File "c:\python27\lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "c:\python27\lib\site-packages\fontTools\ttx.py", line 281, in ttCompile
    ttf.save(output)
  File "c:\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 221, in save
    self._writeTable(tag, writer, done)
  File "c:\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 657, in _writeTable
    self._writeTable(masterTable, writer, done)
  File "c:\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 660, in _writeTable
    tabledata = self.getTableData(tag)
  File "c:\python27\lib\site-packages\fontTools\ttLib\__init__.py", line 671, in getTableData
    return self.tables[tag].compile(self)
  File "c:\python27\lib\site-packages\fontTools\ttLib\tables\C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "c:\python27\lib\site-packages\fontTools\cffLib\__init__.py", line 108, in compile
    topDict.recalcFontBBox()
  File "c:\python27\lib\site-packages\fontTools\cffLib\__init__.py", line 2341, in recalcFontBBox
    bounds = charString.calcBounds()
  File "c:\python27\lib\site-packages\fontTools\misc\psCharStrings.py", line 984, in calcBounds
    self.draw(boundsPen)
  File "c:\python27\lib\site-packages\fontTools\misc\psCharStrings.py", line 979, in draw
    extractor.execute(self)
  File "c:\python27\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\python27\lib\site-packages\fontTools\misc\psCharStrings.py", line 345, in op_callgsubr
    self.execute(subr)
  File "c:\python27\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\python27\lib\site-packages\fontTools\misc\psCharStrings.py", line 345, in op_callgsubr
    self.execute(subr)
  File "c:\python27\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\python27\lib\site-packages\fontTools\misc\psCharStrings.py", line 634, in op_vvcurveto
    dya, dxb, dyb, dyc = args[i:i+4]
ValueError: need more than 2 values to unpack
(Hit any key to exit)
```

Any idea what went wrong? I have the following versions:

Python 2.7.12
Node 8.9.0

I only put in the `OperatorMono-Book.otf` in the original folder

**Comment by DJWassink** [comment]
On linux it builded correctly so I now have the fonts with lig's 😄
So apperantly it's now the font its fault.

Thanks for your awesome work, the lig's look awesome ❤️

**Comment by kiliman** [comment]
Thanks for the error report. I'll take a look.

I'm glad you were able to get it working with Linux.

**Comment by AlekseyPn** [comment]
I installed this fonts with help Windows Bash. Work great!

**Comment by zLoneWolf** [comment]
I get this error too. I've try Windows subsystem for Linux to use Linux Bash on Windows but I encountered this 
![image](https://user-images.githubusercontent.com/35826157/35924911-ef4a85e4-0c56-11e8-8810-16129cc39744.png)

**Comment by zLoneWolf** [comment]
@AlekseyPn How can you do that, I've tried to use Windows subsytem for Linux but I still get the error

**Comment by zLoneWolf** [comment]
@kiliman I've tried various way to install this on windows but it always got the same error as mentioned in this topic so I decided to borrow my friend mac and it run smoothly, now I have my font with ligature. So I think this is the issue with Windows 10.

**Comment by kiliman** [comment]
@zLoneWolf Can you send me one of your Operator Mono fonts and let me compare it with mine? Also include the .ttx files from both the ./original and ./build folders.

Like I said, I'm able to build just fine on Windows 10. In fact, I built the original script on Windows when I was using FontForge.

Thanks!

**Comment by muneebrbaig** [comment]
Hi @kiliman 
Here are the files I tried on Windows 10, using Ubuntu Bash. I'm also getting the same error, from both Windows 10 Command Prompt and Ubuntu Bash.

Thanks for the awesome work though.

[original and build folders.zip](https://github.com/kiliman/operator-mono-lig/files/1790494/original.and.build.folders.zip)

**Comment by kiliman** [comment]
Sorry about that. I did a clean checkout and was able to build it. Here are the versions used. I even tried your version of the original fonts (in case they were different).

```
C:\Projects\operator-mono-lig>node -v
v8.9.4

C:\Projects\operator-mono-lig>python -V
Python 2.7.14

C:\Projects\operator-mono-lig>ttx --version
3.21.2

C:\Projects\operator-mono-lig>build
Building OperatorMonoLig-Book
Dumping ".\original\OperatorMono-Book.otf" to ".\original\OperatorMono-Book.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
Dumping 'DSIG' table...
Reading original font file ./original/OperatorMono-Book.ttx
Patching names
Patching glyphs
Patching gpos
Patching gsub
Patching hmtx
Patching charstrings
Writing ligature font file ./build/OperatorMonoLig-Book.ttx
Done
Compiling ".\build\OperatorMonoLig-Book.ttx" to ".\build\OperatorMonoLig-Book.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'hmtx' table...
Parsing 'DSIG' table...
WARNING: GSUB/GPOS Coverage is not sorted by glyph ids.
C:\Projects\operator-mono-lig>
```

**Comment by muneebrbaig** [comment]
Thanks for the response; but I'm getting same error on Windows 10. However, tried it on Mac and that works.

Thanks once again for the awesome work man!

**Comment by ChuKhaLi** [comment]
@muneebrbaig me too, same error on Windows 10. Could you share with me the font that you built?

**Comment by kiliman** [comment]
@ChuKhaLi can you run the following commands and let me know what versions you have?

```
C:\Projects\operator-mono-lig>node -v
v8.9.4

C:\Projects\operator-mono-lig>python -V
Python 2.7.14

C:\Projects\operator-mono-lig>ttx --version
3.21.2

```

**Comment by ChuKhaLi** [comment]
@kiliman
`C:\Projects\operator-mono-lig>node -v
v8.11.1

C:\Projects\operator-mono-lig>python -V
Python 3.6.5

C:\Projects\operator-mono-lig>ttx --version
3.25.0`

**Comment by kiliman** [comment]
Hmm. I wonder if the issue is with Python 3. I'll have to try it on Windows.
