### ISSUE TITLE
Error: ENOENT: no such file or directory, open './original/OperatorMono-Medium.ttx'

### ISSUE THREAD

**Issue by eBaeza** [kiliman/operator-mono-lig#6]
I get this error when run build.sh, I am using node v8.4.0 

```
➜  operator-mono-lig git:(master) ✗ sh build.sh
rm: original/*.ttx: No such file or directory
build.sh: line 4: ttx: command not found
build.sh: line 5: ttx: command not found
Reading original font file ./original/OperatorMono-Medium.ttx
(node:19784) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open './original/OperatorMono-Medium.ttx'
(node:19784) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Reading original font file ./original/OperatorMono-MediumItalic.ttx
(node:19785) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open './original/OperatorMono-MediumItalic.ttx'
(node:19785) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
build.sh: line 14: ttx: command not found
build.sh: line 15: ttx: command not found
```

**Comment by kiliman** [comment]
Did you install Python/fonttools as specified in the README?

`ttx` is part of the fonttools package that my project uses to convert OTF files into an XML description.

**Comment by eBaeza** [comment]
@kiliman yes 
```
➜  ~ pip freeze
altgraph==0.10.2
bdist-mpkg==0.5.0
bonjour-py==0.3
fonttools==3.15.1 <-----------
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
py2app==0.7.3
pyobjc-core==2.5.1
```

**Comment by jasonhodges** [comment]
I too am getting a similar error

```
/operator-mono-lig]─[±] master ✓                                                       [Thu Sep 07 - 10:08]
└──● sh build.sh
rm: original/*.ttx: No such file or directory
build.sh: line 4: ttx: command not found
build.sh: line 5: ttx: command not found
/Users/../../../operator-mono-lig/index.js:16
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
/Users//../../../operator-mono-lig/index.js:16
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
build.sh: line 14: ttx: command not found
build.sh: line 15: ttx: command not found
```

```
/operator-mono-lig]─[±] master ✓                                                   [Thu Sep 07 - 10:09]
└──● pip freeze
altgraph==0.10.2
bdist-mpkg==0.5.0
bonjour-py==0.3
fonttools==3.15.1 <-----
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
py2app==0.7.3
pyobjc-core==2.5.1
```

**Comment by kiliman** [comment]
Odd. Did you make sure `ttx` is in your path?

![image](https://user-images.githubusercontent.com/47168/30177955-57dd457e-93d5-11e7-93a2-a6282ce3d531.png)

**Comment by jasonhodges** [comment]
I installed fonttools properly as listed in the instructions and you can see in the second image I provided earlier, it is shown. However when I run `which ttx`, I get ttx: not found

I looked under `/usr/local/bin` and ttx is not shown there

currently investingating

**Comment by eBaeza** [comment]
@kiliman No, I don't have it and does no exists

**Comment by jasonhodges** [comment]
Ok, after 
`pip uninstall fonttools` <-- which was installed using `--user` because of hopeful `sudo` advoidance, I ran 
`sudo pip install fonttools`. 
I now get several errors and an empty build directory
```
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
Dumping 'DSIG' table...
/Users/../operator-mono-lig/index.js:16
async function main() {
      ^^^^^^^^
SyntaxError: Unexpected token function
```

```
ERROR: File not found: "build/OperatorMonoLig-Medium.ttx"
```

```
ERROR: File not found: "build/OperatorMonoLig-MediumItalic.ttx"
```

**Comment by kiliman** [comment]
@jasonhodges at least we're making progress. The `async` error is most likely because your version of Node.js is less that 7.6. That's the version that added support for async/await. Upgrade your version of Node.js and see if that helps.

I may end up dumping async/await (although sweet) to make it less painful to use the tool.

**Comment by jasonhodges** [comment]
Ok @kiliman, I used nvm to install node v8.4.0. Once complete, I ran `sh build.sh` once again and it did merge out my Medium and MediumItalic to the build directory.

**Comment by eBaeza** [comment]
Finally I could, i had to install python with homebrew:

```
$ brew install python
$ pip2 install fonttools
$ sh build.sh
```

**Comment by AndrewStobie** [comment]
For the record similarly just did 
```
$ sudo -H pip2 uninstall fonttools
$ brew upgrade python
$ pip2 install fonttools
$ sh build.sh
```

It worked then.

**Comment by timhecker** [comment]
FYI, for Mac users, I advice to run `pip3 install fonttools`, solving mac permissions problems ([https://stackoverflow.com/a/33416270/3191011](url))

**Comment by kiliman** [comment]
@timhecker Can you update the README with the info you found? Thanks!

**Comment by chiangs** [comment]
I get a successfully installed fonttools-4.0.2 using `pip3 install fonttools` but `where ttx` still results in ttx not found.

Any other possible fixes?  Thanks

**Comment by MortimerMarsyja** [comment]
what about for windows users? because I am stuck with the same issue

**Comment by aminelch** [comment]
for ubuntu users 
`sudo apt install fonttools python3-fonttools`
and after installation run 
`./buid.sh `
it workd for me 😀
