### ISSUE TITLE
Error in building

### ISSUE THREAD

**Issue by Hackerbee** [kiliman/operator-mono-lig#63]
```cmd
C:\Users\hackerbee\Downloads\Compressed\operator-mono-lig-master\operator-mono-lig-master>pip3 install fonttools
Collecting fonttools
  Using cached https://files.pythonhosted.org/packages/ab/09/ae90c98d60c15837ac03cf68ac48a189e8907677c8f1c6941f74bf3e5a7f/fonttools-3.26.0-py2.py3-none-any.whl
Installing collected packages: fonttools
  The scripts fonttools.exe, pyftinspect.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\users\hackerbee\appdata\local\programs\python\python36\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed fonttools-3.26.0

C:\Users\hackerbee\Downloads\Compressed\operator-mono-lig-master\operator-mono-lig-master>npm install
npm WARN operator-mono-lig@1.0.0 No repository field.

audited 7 packages in 2.163s
found 0 vulnerabilities


C:\Users\hackerbee\Downloads\Compressed\operator-mono-lig-master\operator-mono-lig-master>build
Building OperatorMonoLig-Book
Dumping ".\original\OperatorMono-Book.otf" to ".\original\OperatorMono-Book.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
Dumping 'DSIG' table...
Reading original font file ./original/OperatorMono-Book.ttx
Patching names
Patching glyphs
Patching gpos
Patching gsub
Patching hmtx
Patching charstrings
Writing ligature font file ./build/OperatorMonoLig-Book.ttx
Done
Compiling ".\build\OperatorMonoLig-Book.ttx" to ".\build\OperatorMonoLig-Book.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'hmtx' table...
Parsing 'DSIG' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 399, in main
    process(jobs, options)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 373, in process
    action(input, output, options)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 291, in ttCompile
    ttf.save(output)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 624, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 628, in _writeTable
    tabledata = self.getTableData(tag)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 646, in getTableData
    return self.tables[tag].compile(self)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\tables\C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\cffLib\__init__.py", line 108, in compile
    topDict.recalcFontBBox()
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\cffLib\__init__.py", line 2340, in recalcFontBBox
    bounds = charString.calcBounds(self.CharStrings)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 984, in calcBounds
    self.draw(boundsPen)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 979, in draw
    extractor.execute(self)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 340, in op_callsubr
    self.execute(subr)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 634, in op_vvcurveto
    dya, dxb, dyb, dyc = args[i:i+4]
ValueError: not enough values to unpack (expected 4, got 2)
(Hit any key to exit)
Building OperatorMonoLig-BookItalic
Dumping ".\original\OperatorMono-BookItalic.otf" to ".\original\OperatorMono-BookItalic.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
Dumping 'DSIG' table...
Reading original font file ./original/OperatorMono-BookItalic.ttx
Patching names
Patching glyphs
Patching gpos
Patching gsub
Patching hmtx
Patching charstrings
Writing ligature font file ./build/OperatorMonoLig-BookItalic.ttx
Done
Compiling ".\build\OperatorMonoLig-BookItalic.ttx" to ".\build\OperatorMonoLig-BookItalic.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'hmtx' table...
Parsing 'DSIG' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 399, in main
    process(jobs, options)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 373, in process
    action(input, output, options)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 291, in ttCompile
    ttf.save(output)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 624, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 628, in _writeTable
    tabledata = self.getTableData(tag)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 646, in getTableData
    return self.tables[tag].compile(self)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\tables\C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\cffLib\__init__.py", line 108, in compile
    topDict.recalcFontBBox()
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\cffLib\__init__.py", line 2340, in recalcFontBBox
    bounds = charString.calcBounds(self.CharStrings)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 984, in calcBounds
    self.draw(boundsPen)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 979, in draw
    extractor.execute(self)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 345, in op_callgsubr
    self.execute(subr)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 340, in op_callsubr
    self.execute(subr)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 564, in op_rmoveto
    self.rMoveTo(self.popallWidth())
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 519, in rMoveTo
    self.pen.moveTo(self._nextPoint(point))
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 514, in _nextPoint
    point = x + point[0], y + point[1]
IndexError: list index out of range
(Hit any key to exit)
Building OperatorMonoLig-Medium
Dumping ".\original\OperatorMono-Medium.otf" to ".\original\OperatorMono-Medium.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
Dumping 'DSIG' table...
Reading original font file ./original/OperatorMono-Medium.ttx
Patching names
Patching glyphs
Patching gpos
Patching gsub
Patching hmtx
Patching charstrings
Writing ligature font file ./build/OperatorMonoLig-Medium.ttx
Done
Compiling ".\build\OperatorMonoLig-Medium.ttx" to ".\build\OperatorMonoLig-Medium.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'hmtx' table...
Parsing 'DSIG' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 399, in main
    process(jobs, options)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 373, in process
    action(input, output, options)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 291, in ttCompile
    ttf.save(output)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 624, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 628, in _writeTable
    tabledata = self.getTableData(tag)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 646, in getTableData
    return self.tables[tag].compile(self)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\tables\C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\cffLib\__init__.py", line 108, in compile
    topDict.recalcFontBBox()
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\cffLib\__init__.py", line 2340, in recalcFontBBox
    bounds = charString.calcBounds(self.CharStrings)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 984, in calcBounds
    self.draw(boundsPen)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 979, in draw
    extractor.execute(self)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 612, in op_rcurveline
    dxb, dyb, dxc, dyc, dxd, dyd = args[i:i+6]
ValueError: not enough values to unpack (expected 6, got 4)
(Hit any key to exit)
Building OperatorMonoLig-MediumItalic
Dumping ".\original\OperatorMono-MediumItalic.otf" to ".\original\OperatorMono-MediumItalic.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
Dumping 'DSIG' table...
Reading original font file ./original/OperatorMono-MediumItalic.ttx
Patching names
Patching glyphs
Patching gpos
Patching gsub
Patching hmtx
Patching charstrings
Writing ligature font file ./build/OperatorMonoLig-MediumItalic.ttx
Done
Compiling ".\build\OperatorMonoLig-MediumItalic.ttx" to ".\build\OperatorMonoLig-MediumItalic.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'hmtx' table...
Parsing 'DSIG' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 399, in main
    process(jobs, options)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 373, in process
    action(input, output, options)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\loggingTools.py", line 372, in wrapper
    return func(*args, **kwds)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttx.py", line 291, in ttCompile
    ttf.save(output)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 172, in save
    writer_reordersTables = self._save(tmp)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 211, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 624, in _writeTable
    self._writeTable(masterTable, writer, done, tableCache)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 628, in _writeTable
    tabledata = self.getTableData(tag)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\ttFont.py", line 646, in getTableData
    return self.tables[tag].compile(self)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\ttLib\tables\C_F_F_.py", line 20, in compile
    self.cff.compile(f, otFont, isCFF2=False)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\cffLib\__init__.py", line 108, in compile
    topDict.recalcFontBBox()
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\cffLib\__init__.py", line 2340, in recalcFontBBox
    bounds = charString.calcBounds(self.CharStrings)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 984, in calcBounds
    self.draw(boundsPen)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 979, in draw
    extractor.execute(self)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 301, in execute
    rv = handler(index)
  File "c:\users\hackerbee\appdata\local\programs\python\python36\lib\site-packages\fontTools\misc\psCharStrings.py", line 634, in op_vvcurveto
    dya, dxb, dyb, dyc = args[i:i+4]
ValueError: not enough values to unpack (expected 4, got 2)
(Hit any key to exit)

C:\Users\hackerbee\Downloads\Compressed\operator-mono-lig-master\operator-mono-lig-master>
```

**Comment by Hackerbee** [comment]
I checked, the site-packages directory was in PATH variable.
I reinstalled everything but still the same error

**Comment by Hackerbee** [comment]
I cloned the repo in clean folder and it is working now.... yay.
Before, I downloaded this repo, not cloned.

Thanks a lot.. 🤗

**Comment by Hackerbee** [comment]
@kiliman @timhecker @marsqing @sjousse 
Can anyone explain why it raised the error?
as error said, 4 args needed but got only 2.

**Comment by backend-dp** [comment]
I spent 1 hour trying to figure why it did that :|.
Never download repos boys!

**Comment by WinterCore** [comment]
I spent 1 hour trying to figure why it did that :|.
Never download repos boys!
