### ISSUE TITLE
Unknown build error, can't install font

### ISSUE THREAD

**Issue by rjacobson16** [kiliman/operator-mono-lig#89]
I am getting an unknown build error on MacOSX, latest Mojave.

Fonts: original font names are `OperatorSsm-Book.otf`. I have renamed the files to fit the scheme outlined in the readme: `OperatorMono-Book.otf`. This results in files in the `build` folder, but when I double click the file, FontBook opens but does not prompt me to install the font. 

Output:
```
Building OperatorMonoLig-Book
Dumping "./original/OperatorMono-Book.otf" to "./original/OperatorMono-Book.ttx"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'name' table...
Dumping 'cmap' table...
Dumping 'post' table...
Dumping 'CFF ' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'hmtx' table...
Dumping 'kern' table...
Dumping 'DSIG' table...
Reading original font file ./original/OperatorMono-Book.ttx
Patching names
Patching glyphs
Patching gpos
Patching gsub
Patching hmtx
Patching charstrings
Writing ligature font file ./build/OperatorMonoLig-Book.ttx
Done
Compiling "./build/OperatorMonoLig-Book.ttx" to "./build/OperatorMonoLig-Book.otf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'name' table...
Parsing 'cmap' table...
Parsing 'post' table...
Parsing 'CFF ' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'hmtx' table...
Parsing 'kern' table...
Parsing 'DSIG' table...
ERROR: Unhandled exception has occurred
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttx.py", line 401, in main
    process(jobs, options)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttx.py", line 375, in process
    action(input, output, options)
  File "/usr/local/lib/python3.7/site-packages/fontTools/misc/loggingTools.py", line 375, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttx.py", line 293, in ttCompile
    ttf.save(output)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 173, in save
    writer_reordersTables = self._save(tmp)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 212, in _save
    self._writeTable(tag, writer, done, tableCache)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 633, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 651, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 70, in compile
    self.table.compile(writer, font)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 710, in compile
    conv.write(writer, font, table, value)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 681, in compile
    conv.write(writer, font, table, value, i)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 681, in compile
    conv.write(writer, font, table, value, i)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 710, in compile
    conv.write(writer, font, table, value)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otConverters.py", line 520, in write
    value.compile(subWriter, font)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otBase.py", line 650, in compile
    table = self.preWrite(font)
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otTables.py", line 564, in preWrite
    glyphIDs = [getGlyphID(glyphName) for glyphName in glyphs ]
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/tables/otTables.py", line 564, in <listcomp>
    glyphIDs = [getGlyphID(glyphName) for glyphName in glyphs ]
  File "/usr/local/lib/python3.7/site-packages/fontTools/ttLib/ttFont.py", line 602, in getGlyphID
    glyphID = d[glyphName]
KeyError: ('zero.num', 'Coverage', 'PairPos[0]', 'Lookup[0]', 'LookupList')
```

**Comment by kiliman** [comment]
Sorry for the late reply. Based on your comment, are you sure you have the Operator **Mono** font? Can you post a screenshot from FontBook?

**Comment by kiliman** [comment]
I'm closing this issue. You can reopen if you're still have a problem. Thanks!
